ingress:
  hostname: jobmgr.staging.mmli1.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"

controller:
  image: moleculemaker/mmli-job-manager:staging

persistence:
  existingClaim: "mmli-clean-job-weights"
  storageClassName: csi-cinder-sc-retain
  storageSize: "100Gi"

mariadb:
  global:
    storageClass: csi-cinder-sc-retain
  enabled: true
  auth:
    username: mmli
    existingSecret: "job-manager-mariadb"

hcaptcha:
  auth:
    existingSecret: "hcaptcha"

extraDeploy:
# Deploy CORS middleware for staging namespace
- apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    name: cors-header
    namespace: staging
  spec:
    headers:
      accessControlAllowCredentials: true
      accessControlAllowHeaders:
      - Origin
      - X-Requested-With
      - Content-Type
      - content-type
      - Accept
      - Authorization
      accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - DELETE
      - POST
      accessControlAllowOriginList:
      - https://clean.frontend.mmli1.ncsa.illinois.edu
      - https://clean.frontend.staging.mmli1.ncsa.illinois.edu
      - https://jobmgr.mmli1.ncsa.illinois.edu
      - https://jobmgr.staging.mmli1.ncsa.illinois.edu

# Enable DecentCI backups
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: backups
    namespace: staging
    labels:
      app.kubernetes.io/name: decentci-backups
      app.kubernetes.io/component: config
  data:
    backups: |
      - backup-name: decentci-backups-jobmgr-db
        schedule: "01 7 * * *"
        database:
          type: mysql
          host: job-manager-staging-mariadb.staging.svc.cluster.local
          auth:
            username: mmli
            database: mmli
            passwordKey: mariadb-password
            existingSecret: job-manager-mariadb
    global: |
      enabled: true
      backup-nfs-path: /taiga/ncsa/radiant/bbfp/mmli1/backups/staging/jobmgr
      backup-nfs-server: taiga-nfs.ncsa.illinois.edu

# Deploy SealedSecret for database credentials
- apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    creationTimestamp: null
    name: job-manager-mariadb
    namespace: staging
  spec:
    encryptedData:
      mariadb-password: AgBWG/Leswcp15h++dObXEKHONqJ3VqTRDhW4Wg/mG1XETtDsxIN8J7SFQI0mfLZ5MNOF/SZa0huPajCS8/BLE+k4zbtps5tEjP2H2pPZOFv+BgoZGWoEi88jGZXPepCPplNSvuzKt0ydxmZXyXLjG4gNKpmSCVHPGGIboCYxRpCyWSDoyOzxn583+9oQwLYmkCrXch+GihvaIvA3ZbRrsw1Q75xNEtK+gjjaRbg8x3nCt5V6w3laALs2Cs69xzQQD/N4K8OKCdIi7vgcI5DCz3oMOdCCcsMLXrSfPwAw3kyEGd+0O0Dv4nBOMCUEhaZsEXgY55Ly6VOx5YuSCFhHywVrAJ/IoSDjM7JblLxO/BU4wEb/w983WnsiHiWuGbsPzNX3fywiwQ4cgavE5VbmiGS4z5RgLW3XSvY4OkUC2hMT2rv0A1rDVs2Q42OffArUbxls4L27mN6gYdT6bXHht6CwGtlmGs3oPlJLuY6laGoUkvky2B5R4wiqjuKEUjwKxUYX6NeeLr2PSngnz+JC/M+haVWw8r2KtgrH490Ei+tzHd6mMLrQchdsxksZA0UP9ZGiRmzGuoOOQiDQXByKNFB1RcLqrDp8kAyzIrF+znOxRk5/ZfzjpFdDIIsZpcWB57d1iO0099R0c+ZC8g03JlDxG9cdEYeDfxrohbaf6elZ+P12cP/zUB1rnPP5gTyoB8Kf2Mz5irc2os4qbe7r4k4q/3NxG0h0l52S/KIy04=
      mariadb-replication-password: AgAgprULdX0UVmfABxZvjj7A12+FCrvsS2tvNJGl5cPyGw9+ijGzMoPumRqxzs9sr3BsN54hoDXUSZ1LIhYh+FeiQNF9SND83z/rba7qehCa+l17u4uXrTn5U8QmURTEiKmNze4zBSWl9uxLyYerI03wkWtT09PPyc1Z+Tj3CY/3kmuLskUe6xZXq+dFopdJZM8/4KlPywi8vC51P2vwsFHTS/IwcWHgA/al6JwqtgRWvgDO4gfMyt8RxbGwEornUxRF+gpbIzDe4jeFtO2AuJVH5OmEDjftNUSEi0Cf2O9pEqyMExZ1lj53B/2eqpLSlZUiAJDEWZ5HNW9ZXpyFPB/fKA8ciqambvt4FqHx+8kkXiSCqDtzMrR6q1bu++Q2pG/UqYPOTYzrKDbZg9tnl3MKvXEJYX0trlt+E6Mvti77NIGTf7WEWdEvFWQY5njvThgoHDTm5vD2enLMMTKTisN3jN3mwtB1XBhAmoGsybo97LHy1cwfprs5Pz1RL5NmNzGcizkgMEeg5HEBCoK47X7vlda5Dk+t9fg0EDrfDEGZSQpFOiuqPECp6LgCW81XH48f+Su8unGhZi+7JNBa/gzpOmqxJkX8gat4y+3CuR4YjYqIdz1vEcPU9WZ3tDIBsK5MgwpsLG0MwSsVnam1RrrTEsTcwYIlPneTAdJ8eaDZSCcplqwV2y5GvIMsns4DMAnbUIwBuPolR1qQUNONIvsJxFB7+MvycZLTFb/dZL8=
      mariadb-root-password: AgA0eRzIwTDzKpiLqLOeGv9gHtASVIY7RxKAdonuhTAG2+A7EHHqAZtpgdHfCV0d2HbHALzKyRKxXBEPPvDnYfpRt7myC/ls0VNQBfqAuRXQAybRuQSt2tS08J/YmmD/8nGrkFjicr+N+voUMjVyfTc573NduJYFMUl+OZG/BtAa4sImCaINbMwEO71YRER4qt+eIttJK5eUW/uhlESC0BJbkIPUYFwFlxaFqx+8+flgQulJslCbyOdjlHVKohQQcwrLqRy01+4w18nc/W7439qOea4Mx8u5sH9VMLv7ELAOlcciC5RoWuIJIH50E2voVHc7cgnwLk9W8dV6cexTcqRHX/2dtCIm4O2mI/Uov1gViqUbwMhDIeiQbbRa5A32qbySeKuG4X1miurLyJi/j9Bi140g4qKzG5NGVCy8PvbEpyO5+t0rfInZX0cYTRaNKSWq/vyNmEsTbIEhfoZynpECCCbo9cXbGXjtDN2RAtittXAJQvrwGVSbBYihWTAX8CFeaMTrkRb/hz3L11u9oXexJBjcXsYHqoJ9ZrvKrP5QDPrPS3TmADTe+rqBaRsNOlVuw/ITrxdwo+AsQAowksTWLogo2kxoNUbU9dvMEMnw6QERhScj+ReShhW/KpikdObrWaI8nbf3xgicWubSgp9TFs21XrK9BJCWhP5vvoqoQXaQgcq4Al1sFzgsU6fDnpnKLK3dL5sO8cjyrm3GaJGYTU6NDS5iWotOZnRswkI=
    template:
      metadata:
        creationTimestamp: null
        name: job-manager-mariadb
        namespace: staging
      type: Opaque

# Deploy SealedSecret for hcaptcha secret
- apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    creationTimestamp: null
    name: hcaptcha
    namespace: staging
  spec:
    encryptedData:
      secret: AgBs9ztEZ1LpeC6NaSEozqaE/FE6YdqyOfRFRzkCE1KuleIvxHWY2POuOd/n2vJgjzvi8VquRStDxUTRjhWfeSmrxN963BKn3rX2GAG1f7FYAsdDkch72L7PFe4pctd+62VrmFb4CRgE86b9YAkO3PUm5IAEd3IFZuyzzaUiFVGQSbzgpjxrNb1fGatFnYbpkOVkPmbP/orq3DTRUJds7/IfrBFP2bxe2fC8W0Fqa4v1RTRYyx6uyPZzGsmogCHTh6RY6jzYouXnPQa5elhDXfNQlHcf/owqENq5j9dkUODt2WXbJLPQJQK9qlSNto/EfO6IpfWeJV6Rh7TS2NB95WU8sNK80F8LpsZoWEyvbYfNw+DnvlJkZkCeLaWAvs9vIYTIkocR/kNPVdxhYXm9kZdYhy4RHhTaOZKfbfVx7u/Sek2a3soqY3nM5BOHQnuEcosy/iTzM7K8ZGEn2IBAx3uQ1dPp/4IfOVkJk0FVAQwLLtBBVVf7hCNeqq5+AY0qxsQ9cfiJF2JVIzryXvEhEPBercZvln5TSXQNM5kk1P0p89mpycGy2CcG/Yl8DPoC6vPX234dLLwzTKld3eJyNR0Y7+HdEMganLaND1tQOaAZ87/2ZPoZWi7axtdNYzQHliqa1/mRVlvI8p/jWaOMUU0kRBi1DBZcaa0JaxclcBfJCs8zU7JZbzugoY+OfTDwP9etTGuB9JEiAEtyNh5l/Tqfz1deslr0hVxOAcBc3zoDutSNl37Vqi+XaWk=
    template:
      metadata:
        creationTimestamp: null
        name: hcaptcha
        namespace: staging
      type: Opaque

config:
  server:
    protocol: "https"
    ## API hostname. Must match the ingress.hostname value.
    hostName: "jobmgr.staging.mmli1.ncsa.illinois.edu"
    namespace: "staging"
  oauth:
    userInfoUrl: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/userinfo"
  uws:
    ## Server working directory to store generated job data
    workingVolume:
      claimName: "mmli-clean-job-weights"
      mountPath: "/uws"
      subPath: "uws"
    ## Central data volumes to be mounted in job containers
    volumes:
      - name: 'job-output'
        mountPath: '/app/data/inputs'
        subPath: 'input'
        claimName: 'mmli-clean-job-weights'
      - name: 'job-output'
        mountPath: '/app/results/inputs'
        subPath: 'output'
        claimName: 'mmli-clean-job-weights'
      - name: 'job-output'
        mountPath: '/root/.cache/torch/hub/checkpoints'
        subPath: 'weights'
        claimName: 'mmli-clean-job-weights'
    # - name: data
    #   claimName: mmli-data-pvc
    #   mountPath: "/data/mmli"
    #   subPath: ""
    #   readOnly: true
