ingress:
  hostname: jobmgr.localhost
  tls: false
  annotations: {}

controller:
  image: moleculemaker/mmli-job-manager:dev

persistence:
  # Set this to use a particular StorageClass
  # Unset this to use a clsuter default StorageClass
  storageClassName: ""
  storageSize: "1Gi"

# https://artifacthub.io/packages/helm/bitnami/mariadb?modal=values
mariadb:
  enabled: true
  auth:
    # Use an existing secret - this overrides username, password, and rootPassword
    # existingSecret: ""

    # Local development only - hardcode credentials here for simplicity
    # rootPassword: ""
    # password: ""

    # Set the name of you mariadb user
    username: "mmli"

    # Set the name of your mariadb database
    database: "mmli"
