ingress:
  ingressClassName: nginx

#persistence:
#  storageClassName: hostpath

controller:
  image: moleculemaker/mmli-job-manager:dev

mariadb:
  enabled: true
#  global:
#    storageClass: hostpath
  auth:
    existingSecret: ""
    rootPassword: "mmli"
    password: "mmli"
    username: "mmli"
    database: "mmli"
