ingress:
  hostname: jobmgr.proxy.localhost
  tls: false
  annotations: {}

jobSubmitIngress:
  hostname: jobmgr.proxy.localhost
  tls: false
  annotations: {}

controller:
  image: moleculemaker/mmli-job-manager:main


persistence:
  # Set this to use a particular StorageClass
  # Unset this to use the cluster default StorageClass
  storageClassName: ""
  existingClaim: ""
  storageSize: "10Gi"

  # EXPERIMENTAL: Set this to enable mounting a directory into this volume from host
  hostpath: ""

hcaptcha:
  auth:
    existingSecret: ""

# https://artifacthub.io/packages/helm/bitnami/mariadb?modal=values
mariadb:
  enabled: true
  auth:
    # Use an existing secret - this overrides username, password, and rootPassword
    # existingSecret: ""

    # Local development only - hardcode credentials here for simplicity
    # rootPassword: ""
    # password: ""

    # Set the name of you mariadb user
    username: "mmli"

    # Set the name of your mariadb database
    database: "mmli"

# Override server.yaml at runtime
config: {}
