ingress:
  #ingressClassName: nginx
  ingressClassName: traefik
  hostname: jobmgr.proxy.localhost
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://clean.proxy.localhost,https://molli.proxy.localhost,http://localhost:4200"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    traefik.ingress.kubernetes.io/router.middlewares: mmli-cors-header@kubernetescrd

jobSubmitIngress:
  #ingressClassName: nginx
  ingressClassName: traefik
  hostname: jobmgr.proxy.localhost
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://clean.proxy.localhost,https://molli.proxy.localhost,http://localhost:4200"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    traefik.ingress.kubernetes.io/router.middlewares: mmli-cors-header@kubernetescrd,mmli-ip-ratelimit@kubernetescrd

persistence:
  existingClaim: "mmli-clean-job-weights"  # use locally mounted data instead

  # Override the default StorageClass
  storageClassName: hostpath

  # EXPERIMENTAL: Set this to enable mounting a directory into this volume from host
  #hostpath: /Users/lambert8/workspace/mmli/mmli-job-manager/data


controller:
  image: moleculemaker/mmli-job-manager:staging

mariadb:
  enabled: true
#  global:
#    storageClass: hostpath
  auth:
    existingSecret: ""
    rootPassword: "mmli"
    password: "mmli"
    username: "mmli"
    database: "mmli"

config:
  server:
    protocol: "https"
    ## API hostname. Must match the ingress.hostname value.
    hostName: "jobmgr.proxy.localhost"
    namespace: "job-manager"
  hcaptcha:
    secret: "ChangeThisInProduction"
  oauth:
    userInfoUrl: "http://oauth2-proxy.mmli.svc.cluster.local/oauth2/userinfo"
  uws:
    imagePullSecret: "regcred"
    ## Server working directory to store generated job data
    workingVolume:
      claimName: "mmli-clean-job-weights"
      mountPath: "/uws"
      subPath: "uws"
    ## Central data volumes to be mounted in job containers
    volumes:
      - name: 'job-output'
        mountPath: '/app/data/inputs'
        subPath: 'input'
        claimName: 'mmli-clean-job-weights'
      - name: 'job-output'
        mountPath: '/app/results/inputs'
        subPath: 'output'
        claimName: 'mmli-clean-job-weights'
      - name: 'job-output'
        mountPath: '/root/.cache/torch/hub/checkpoints'
        subPath: 'weights'
        claimName: 'mmli-clean-job-weights'
    # - name: data
    #   claimName: mmli-data-pvc
    #   mountPath: "/data/mmli"
    #   subPath: ""
    #   readOnly: true
