ingress:
  ingressClassName: nginx

#persistence:
#  storageClassName: hostpath

# Override config/server.yaml
config:
  server:
    hostName: "jobmgr.localhost"

mariadb:
  enabled: true
#  global:
#    storageClass: hostpath
  auth:
    rootPassword: "mmli"
    password: "mmli"
    username: "mmli"
    database: "mmli"
