{{- if .Values.backups.enabled | default false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backups
  labels:  
    app.kubernetes.io/name: decentci-backups
    app.kubernetes.io/component: config
data:
  backups: |
    - backup-name: decentci-backups-jobmgr-db
      schedule: "01 7 * * *"
      database:
        type: mysql
        host: {{ .Release.Name }}-mariadb.{{ Release.Namespace }}.svc.cluster.local
        auth:
          username: mmli
          database: mmli
          passwordKey: mariadb-password
          existingSecret: job-manager-mariadb
  global: |
    enabled: true
    backup-nfs-path: /taiga/ncsa/radiant/bbfp/mmli1/backups/staging/jobmgr
    backup-nfs-server: taiga-nfs.ncsa.illinois.edu
{{- end }}
