{{- if not .Values.persistence.existingClaim }}
{{- if .Values.persistence.hostpath }}
# Manually link PV for hostpath volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-manager-pv
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistence.hostpath }}
  persistentVolumeReclaimPolicy: Recycle
---
{{- end }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: job-manager-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
{{- if .Values.persistence.hostpath }}
  volumeName: job-manager-pv
{{- end }}
{{- end }}
