server:
  protocol: "https"
  port: 8888
  debug: true
  ## API basepath. Must match an ingress in the ingress.basepaths list.
  apiBasePath: "api/v1"
  basePath: ""
  ## API hostname. Must match the ingress.hostname value.
  hostName: "jobmgr.mmli1.ncsa.illinois.edu"
  logLevel: "DEBUG"
  kubeconfig: "/opt/kubeconfig"
  namespace: "job-manager"
db:
  host: ""
  user: ""
  pass: ""
  database: ""
hcaptcha:
  secret: "ChangeThisInProduction"
oauth:
  userInfoUrl: "http://oauth2.proxy.local/oauth2/userinfo"
  cookieName: "_oauth2_proxy"
email:
  server: "smtp.ncsa.uiuc.edu"
  fromEmail: "devnull+clean@ncsa.illinois.edu"
  fromName: "no-reply-CLEAN"

clean:
  job:
    image: "moleculemaker/clean-image-amd64:latest"


molli:
  job:
    image: "moleculemaker/molli:ncsa-workflow"

uws:
  job:
    monitorEnabled: false
    imageJobMonitor:
      repository: "moleculemaker/mmli-job-manager:latest"
      pullPolicy: "Always"
    image:
      repository: "moleculemaker/clean-image-amd64:latest"
      pullPolicy: "Always"
      ## Image pull secrets if necessary
      # pullSecrets:
      # - name: my-secret
      pullSecrets:
      - regcred
    ## Abort jobs after 3 days regardless of their behavior
    activeDeadlineSeconds: 259200
    ## Cleanup completed/failed jobs after 12 hours
    ttlSecondsAfterFinished: 43200
    ## Poll the log file for changes every `logFilePollingPeriod` seconds
    logFilePollingPeriod: 300
    ## CAUTION: Discrepancy between the UID of the image user and the mmli API server UID
    ##          will create permissions problems. For example, if the job UID is 1001 and
    ##          the server UID is 1000, then files created by the job will not in general
    ##          allow the server to delete them when cleaning up deleted jobs.
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      # fsGroup: 202
    resources:
      limits:
        cpu: "1"
        memory: "16Gi"
      requests:
        cpu: "1"
        memory: "12Gi"
  ## Server working directory to store generated job data
  workingVolume:
    claimName: "mmli-clean-job-weights"
    mountPath: "/uws"
    subPath: "uws"
  ## Central data volumes to be mounted in job containers
  volumes:
    - name: 'job-output'
      mountPath: '/app/data/inputs'
      subPath: 'input'
      claimName: 'mmli-clean-job-weights'
    - name: 'job-output'
      mountPath: '/app/results/inputs'
      subPath: 'output'
      claimName: 'mmli-clean-job-weights'
    - name: 'job-output'
      mountPath: '/root/.cache/torch/hub/checkpoints'
      subPath: 'weights'
      claimName: 'mmli-clean-job-weights'
  # - name: data
  #   claimName: mmli-data-pvc
  #   mountPath: "/data/mmli"
  #   subPath: ""
  #   readOnly: true
